development:
  dialect: postgres
  database: bookings
  user: postgres
  password: 12345
  host: 127.0.0.1
  pool: 5

test:
  url: {{env0r "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/myapp_test"}}

production:
  url: {{env0r "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/myapp_production"}}